# application.yml

spring:
  profiles:
    active: dev
  application:
    name: email-service

staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN}
    deploy-env: ${DEPLOY:V2}
  aliyun-enable: ${ALIYUN_ENABLE}
  aliyun-access-key: ${ALIYUN_ACCESS_KEY}
  aliyun-access-secret: ${ALIYUN_ACCESS_SECRET}
  mail-enable: ${MAIL_ENABLE}
  mail-host: ${MAIL_HOST}
  mail-port: ${MAIL_PORT}
  mail-protocol: ${MAIL_PROTOCOL}
  mail-username: ${MAIL_USERNAME}
  mail-password: ${MAIL_PASSWORD}
